import 'package:flutter_test/flutter_test.dart';
import 'package:omi/utils/display_text.dart';

void main() {
  test('strips Ella display prefixes without removing the wing', () {
    expect(stripEllaDisplayPrefix('[Ella] A good afternoon'), 'A good afternoon');
    expect(stripEllaDisplayPrefix('[ella]: Remember the appointment'), 'Remember the appointment');
    expect(stripEllaDisplayPrefix('🪽 [Ella] Family lunch'), '🪽 Family lunch');
  });

  test('retains whether the content was generated by Ella', () {
    expect(parseEllaDisplayValue('[Ella] A good afternoon').isEllaGenerated, isTrue);
    expect(parseEllaDisplayValue('A generic summary').isEllaGenerated, isFalse);
  });

  test('restores the source marker when an Ella title is saved', () {
    expect(
      persistEllaDisplayValue('Updated title', isEllaGenerated: true),
      '[Ella] Updated title',
    );
    expect(
      persistEllaDisplayValue('Generic title', isEllaGenerated: false),
      'Generic title',
    );

    final persistedWingTitle = persistEllaDisplayValue(
      parseEllaDisplayValue('🪽 [Ella] Family lunch').text,
      isEllaGenerated: true,
    );
    final roundTripWingTitle = parseEllaDisplayValue(persistedWingTitle);
    expect(roundTripWingTitle.text, '🪽 Family lunch');
    expect(roundTripWingTitle.isEllaGenerated, isTrue);
  });

  test('leaves unprefixed content unchanged', () {
    expect(stripEllaDisplayPrefix('🪽 Family lunch'), '🪽 Family lunch');
    expect(stripEllaDisplayPrefix('A good afternoon'), 'A good afternoon');
  });
}
