// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7FO-lg7wlMYpU19G_6aEPwLaHVVaLnG8',
    appId: '1:374648418085:android:de181b5b4681b7a1afb513',
    messagingSenderId: '374648418085',
    projectId: 'omi-dev-ca005',
    storageBucket: 'omi-dev-ca005.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7FO-lg7wlMYpU19G_6aEPwLaHVVaLnG8',
    appId: '1:374648418085:ios:1b9e915bea2c5eb56874cc',
    messagingSenderId: '374648418085',
    projectId: 'omi-dev-ca005',
    storageBucket: 'omi-dev-ca005.firebasestorage.app',
    iosClientId: '374648418085-53ldb3s1gc83f557f83huc1q56t7k5ui.apps.googleusercontent.com',
    iosBundleId: 'com.ellaaicare.ella',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7FO-lg7wlMYpU19G_6aEPwLaHVVaLnG8',
    appId: '1:374648418085:web:e1b83d713c04245cafb513',
    messagingSenderId: '374648418085',
    projectId: 'omi-dev-ca005',
    authDomain: 'omi-dev-ca005.firebaseapp.com',
    storageBucket: 'omi-dev-ca005.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7FO-lg7wlMYpU19G_6aEPwLaHVVaLnG8',
    appId: '1:374648418085:ios:1b9e915bea2c5eb56874cc',
    messagingSenderId: '374648418085',
    projectId: 'omi-dev-ca005',
    storageBucket: 'omi-dev-ca005.firebasestorage.app',
    iosClientId: '374648418085-53ldb3s1gc83f557f83huc1q56t7k5ui.apps.googleusercontent.com',
    iosBundleId: 'com.ellaaicare.ella',
  );
}